### ISSUE TITLE
Dates loaded from bootstrap aren't correctly displayed

### ISSUE THREAD

**Issue by poljpocket** [ese-unibe-ch/ese2011-team3#100]
WOW ISSUE 100 xD

I'm working on a bigger bootstrap for us to have more data to test on.

Somehow, I noticed that the dates loaded from bootstrap aren't correct.

An event in the bootstrap like this

Event(polj_uni_5):
name: Einfuehrung in Software Engineering
owner: polj
calendars: [polj_uni]
start: 2011-10-21 13:00:00
end:   2011-10-21 16:00:00
isPublic: true
note: Computer Science Semester 3 Lecture

shows in the app as

Einfuehrung in Software Engineering - (public)  edit | delete
2011-10-21, 15:00 - 2011-10-21, 18:00
Note: Computer Science Semester 3 Lecture
Followers: poljpocket (owner)

So, the hours are changed. And it's exactly two hours for every event. I assume this is GMT --> GMT + 2 (because we are having daylight saving time here still).

@lexruee any idea how to specify timezones in bootstrap?

When I edit the event in app, everything is perfectly fine. So there is no timezone shift.

**Comment by lexruee** [comment]
Indeed that's strange, I will investigate that bug. I'm online...
Could be a  bug in the setters of the event model. Or the format is wrong, the yaml spec says:
Example 2.22. Timestamps

canonical: 2001-12-15T02:59:43.1Z
iso8601: 2001-12-14t21:59:43.10-05:00
spaced: 2001-12-14 21:59:43.10 -5
date: 2002-12-14

source: http://www.yaml.org/spec/1.2/spec.html

-----Ursprüngliche Nachricht-----
Von: Julian Pollak [mailto:reply@reply.github.com] 
Gesendet: Samstag, 29. Oktober 2011 14:41
An: Alexander Rüedlinger
Betreff: [ese2011-team3] Dates loaded from bootstrap aren't correct (#100)

I'm working on a bigger bootstrap for us to have more data to test on.

Somehow, I noticed that the dates loaded from bootstrap aren't correct.

An event in the bootstrap like this

Event(polj_uni_5):
name: Einfuehrung in Software Engineering
owner: polj
calendars: [polj_uni]
start: 2011-10-21 13:00:00
end:   2011-10-21 16:00:00
isPublic: true
note: Computer Science Semester 3 Lecture

shows in the app as

Einfuehrung in Software Engineering - (public)  edit | delete
2011-10-21, 15:00 - 2011-10-21, 18:00
Note: Computer Science Semester 3 Lecture
Followers: poljpocket (owner)

So, the hours are changed. Sometimes it's one hour, or like here, sometimes up to three hours.

@lexruee any idea what this might be? Timezones aren't possible, because of the inconsequent time shifts...

## 

Reply to this email directly or view it on GitHub:
https://github.com/ese-unibe-ch/ese2011-team3/issues/100
