### ISSUE TITLE
popup for [overlapping events]

### ISSUE THREAD

**Issue by wuschu** [ese-unibe-ch/ese2011-team3#114]
when a new event is created, check before submitting if the new event overlaps with any existing event. 
if it has an overlapping event, show a popup that asks you either to continue or to cancel the action.

**Comment by lexruee** [comment]
I suggest, we splitt this feature into two issues.

This feature consists of two parts:
1) the popup which will request the overlapping information with ajax and jquery. @poljpocket
2) a controller method which will provide those informationen in JSON-Style. @lexruee

**Comment by lexruee** [comment]
@poljpocket
In the branch popup you'll find the method Calendars#overlappingEvents(String startDate, String endDate).
This controller method can be accessed by http://localhost:9000/calendars/overlaps/2011-10-27-10:00/2011-10-27-12:00  .
This HTTP-request will give you the following response in JSON format:
{
  "isOverlapping": true,
  "events": [
    {
      "name": "long event",
      "start": "2011-10-12 10:00",
      "end": "2011-11-12 12:00"
    }
  ]
}

In this example above, an overlapping event has been detetced, so that  isOverlapping is true. As further information all the overlapping events in given time interval (startDate /endDate) are transmitted. 

If there are no overlapping events, then the flag isOverlapping is false, and the event array in this JSON-Message is empty.
Such a message looks as follows:

{
  "isOverlapping": false,
  "events": [ ]
}

**Comment by poljpocket** [comment]
Once again, I don't need the events that lead to an overlapping situation. A simple

{"isOverlapping": true}

is enough. But leave it there since you already programmed it now, I'm just not gonna use it that way. :-)

**Comment by poljpocket** [comment]
This one is done, the bug (as in #124) remains!
