### ISSUE TITLE
"all users list" must only contain the contacts of the user

### ISSUE THREAD

**Issue by poljpocket** [ese-unibe-ch/ese2011-team3#50]
Until now, the view that lists all other users really displays all other users. But the requirement for Iteration 1 was to only have your contacts in the "all other users" list. Maybe, we shall rename this list to "show my contacts" or something like that.

**Comment by wuschu** [comment]
actually i did get it another way. 
that on the homepage where you see all the calendars listed, there should also be listed your contact... 
in addition there should be a link like already existing "all other users". 
so that you have the possibility to see every user but not forced to list them on your homepage. 

am i wrong?

**Comment by poljpocket** [comment]
True.

Then we have to duplicate this page. The one will be "all users" and the other will be "all contacts". Right?
